FROM python:3.9

WORKDIR /app

RUN apt-get update -y && apt-get upgrade -y && \
    python -m pip install --upgrade pip && \
    pip install dvc==2.11.0
COPY . /app

RUN pip install -r requirements.txt 

CMD ["dvc", "repro"]