FROM python:3.9

WORKDIR /app

RUN apt-get update -y && apt-get upgrade -y && \
    python -m pip install --upgrade pip && \
    pip install dvc==2.11.0

COPY ./endpoint.py /app

RUN pip install fastapi uvicorn

EXPOSE 8000

CMD ["python", "endpoint.py"]