FROM python:3.9

WORKDIR /app

# RUN addgroup --gid 1024 serge && \
#     adduser --disabled-password --home /home/serge --ingroup serge serge --gecos "" && \
#     chown -R serge:serge /app

RUN apt-get update -y && apt-get upgrade -y && \
    python -m pip install --upgrade pip && \
    pip install dvc==2.11.0

# COPY ./*.py requirements.txt ./
# COPY ./*.py ./*.txt  ./
COPY . /app

RUN pip install -r requirements.txt 

CMD ["dvc", "repro"]