version: '3.7'

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mlflow_models
      MYSQL_USER: serge
      MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - net
  
  train_model:
    container_name: trianing_mlflow
    build: 
      context: .
      dockerfile: Dockerfile_mlflow
    command: dvc repro
    links:
      - "mflow_models:mlflow_models"
    networks:
      - net
    depends_on:
        - mlflow_server

  mlflow_server:
    restart: always
    image: imranq2/mlflow_server
    container_name: mlflow_server
    networks:
      - net
    ports:
        - 5001:5001
    environment:
        - BACKEND=mysql+pymysql://serge:passpass@mysql_db:3306/mlflow_models
        - ARTIFACTS=/mlruns
    volumes:
        - ./mlruns:/mlruns
    command: 
        - sh    # (sh allows for var substitution of BACKEND and ARTIFACTS)
        - -c
        - mlflow server 
            --port 5001
            --host 0.0.0.0
            --backend-store-uri $${BACKEND} 
            --default-artifact-root $${ARTIFACTS}
    depends_on:
        - mysql_db

networks:
  net:
    driver: bridge
