stages:
  get_data:
    cmd: python get_data.py 
    deps: 
      - get_data.py 
    outs:
      - ./raw.csv
  preprocessing:
    cmd: python process.py
    deps:
      - process.py
      - ./raw.csv
    outs:
      - ./processed.csv
  vectorization:
    cmd: python vectorize.py 
    deps:
      - vectorize.py
      - ./processed.csv
    outs: 
      - ./vectorized.parquet
  train_model:
    cmd: python train.py 
    deps:
      - train.py
      - ./vectorized.parquet
    outs:
      - ./clf.pkl
      - ./vectorized_valid.parquet
  validation_metrics:
    cmd: python validation.py
    deps:
      - validation.py
      - ./vectorized_valid.parquet
      - ./clf.pkl
    metrics:
      - metrics.json:
          cache: true
