
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-model-deployment
  labels:
    app: train-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-model
  template:
    metadata:
      labels:
        app: train-model
    spec:
      containers:
      - name: train-model
        image: sergeychuvakin/mlflow_simple_example:v0.1

--- 

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer # NodePort # ClusterIP (default)
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30100