
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web
        image: sergeychuvakin/simple_endpoint:v0.1
        ports:
        - containerPort: 8000

--- 

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort # ClusterIP is default
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100