apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow-tracking-server
  name: mlflow-tracking-server
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mlflow-tracking-server-pods

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-configmap
data:
  ARTIFACT_STORE: "/mlruns"
  # The DB_NAME is the same as the postgresqlDatabase value 
  # set in the helm chart while deploying PostgreSQL using Kubeapps.
  DB_NAME: "mlflow-tracking-server-database"
  # The DB_USERNAME is the same as the postgresqlUsername value 
  # set in the helm chart while deploying PostgreSQL using Kubeapps.
  DB_USERNAME: "admin"
  # The DB_URL will be the same as the DNS displayed under "Installation Notes"
  # section seen after deploying PostgreSQL using Kubeapps
  DB_URL: "mysql+pymysql://serge:passpass@db-sql:3306/mlflow_models"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
  labels:
      app: mlflow-tracking-server
spec:
  # The replica count is kept to one for simplicity purposes.
  # To create a highly available app, the replica count would
  # be higher.
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-tracking-server-pods
  template:
    metadata:
      labels:
        app: mlflow-tracking-server-pods
    spec:
      containers:
        - name: mlflow-tracking-server-pod
          # The docker image is pulled from dockerhub.
          image: aahansingh/applied-mlops:mlflow-tracking-server-gcloud
          imagePullPolicy: Always
          env: # we extract the values we set in the configmap and mount them as environmen variables in the pods.
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow-tracking-server-database-postgresql
                key: postgresql-password
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_USERNAME
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_URL
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_NAME
          - name: ARTIFACT_STORE
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: ARTIFACT_STORE
          # Remember the secret we created before? That will be mounted in the pod as a file.
          volumeMounts:
          - name: mlflow-gcloud-credentials
            mountPath: "/mlruns"
            readOnly: true
      volumes:
      - name: mlflow-gcloud-credentials
        secret:
          secretName: mlflow-gcloud-credentials